# Generated by Django 5.1.2 on 2024-10-23 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "is_visible",
                    models.BooleanField(default=True, verbose_name="Видимый"),
                ),
            ],
            options={
                "verbose_name": "Посты",
                "verbose_name_plural": "Пост",
            },
        ),
    ]
