# Generated by Django 5.1.2 on 2024-10-27 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="postrating",
            name="unique_post_user_rating",
        ),
    ]
