# Generated by Django 5.1.2 on 2024-10-24 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "verbose_name": "Пользователи",
                "verbose_name_plural": "Пользователь",
            },
        ),
    ]
