# Generated by Django 5.1.2 on 2024-10-23 16:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "top_level_domain",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=200),
                        blank=True,
                        size=None,
                        verbose_name="Домен верхнего уровня",
                    ),
                ),
                (
                    "calling_codes",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=django.contrib.postgres.fields.ArrayField(
                            base_field=models.IntegerField(), size=None
                        ),
                        blank=True,
                        size=None,
                        verbose_name="Телефонные коды",
                    ),
                ),
                ("capital", models.CharField(max_length=255, verbose_name="Столица")),
                (
                    "alt_spellings",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=200),
                        blank=True,
                        size=None,
                        verbose_name="Альтернативные написания",
                    ),
                ),
            ],
            options={
                "verbose_name": "Страны",
                "verbose_name_plural": "Страна",
            },
        ),
    ]
