# Generated by Django 5.1.2 on 2024-10-27 12:32

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("countries", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="country",
            name="slug",
            field=autoslug.fields.AutoSlugField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
