# Generated by Django 5.1.2 on 2024-10-27 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("countries", "0003_country_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="country",
            name="alpha_code_iso_2",
            field=models.CharField(
                default=1, max_length=255, verbose_name="Верхний код 2"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="country",
            name="alpha_code_iso_3",
            field=models.CharField(
                default=1, max_length=255, verbose_name="Верхний код 3"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="country",
            name="region",
            field=models.CharField(default=1, max_length=255, verbose_name="Регион"),
            preserve_default=False,
        ),
    ]
