# Generated by Django 5.1.2 on 2024-10-27 15:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "countries",
            "0004_country_alpha_code_iso_2_country_alpha_code_iso_3_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="country",
            name="calling_codes",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=django.contrib.postgres.fields.ArrayField(
                    base_field=models.CharField(max_length=200), size=None
                ),
                blank=True,
                null=True,
                size=None,
                verbose_name="Телефонные коды",
            ),
        ),
    ]
