# Generated by Django 5.1.2 on 2024-10-27 11:30

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tags", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="slug",
            field=autoslug.fields.AutoSlugField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
